# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 python:3.10-slim
 
# Set the working directory in the container
WORKDIR /app
 
# Copy the entire book_catalog directory into the container
COPY book_catalog/ .
 
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
 
# Make port 8000 available to the world outside this container
EXPOSE 8000
 
# Define environment variable
ENV DATABASE_URL=postgresql://sit722_part2_lrsq_user:lItE3Vvs0bZetw1G83nzRd4RuVCBrvgV@dpg-cr3emt2j1k6c73dlbdlg-a.oregon-postgres.render.com:5432/sit722_part2_lrsq
 
# Run app.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
 
 